[package]
name = "LD41"
version = "0.1.0"
authors = ["qfeys <qfeys@skynet.be>"]

[dependencies]
piston = "0.36.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.45.0"
piston2d-opengl_graphics = "0.52.0"
hprof = "0.1.3"
console = "0.6.1"
rand = "0.3"